name: Deploy to FTP (InfinityFree)

on:
  push:
    branches:
      - auto-deploy

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: Deploy via LFTP
        run: |
          lftp -e "
            set ftp:ssl-allow no;
            set ftp:passive-mode yes;
            set net:timeout 30;
            set net:max-retries 2;
            set net:reconnect-interval-base 5;
            open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@ftpupload.net:21;
            mirror --reverse --delete --verbose \
              --exclude .git/ \
              --exclude .env \
              --exclude README.md \
              --exclude composer.lock \
              --exclude node_modules/ \
              --exclude vendor/ \
              --exclude tests/ \
              ./ /htdocs/;
            bye
          "

