name: Deploy to FTP (InfinityFree)

on:
  push:
    branches:
      - main
      - test

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to FTP (InfinityFree)
        uses: appleboy/ftp-action@v0.1.4
        with:
          host: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local_dir: ./
          remote_dir: /htdocs/
          passive: true
          debug: true
          timeout: 600
          exclude: |
            .git*
            README.md
            .env
            composer.lock
            node_modules
            vendor
            tests

